CREATE DATABASE IF NOT EXISTS fit;

USE fit;

CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  address VARCHAR(255),
  gender VARCHAR(20),
  hobbies VARCHAR(255),
  lastLogin DATETIME NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
